M7 db
crowdproj/crowdproj-ratings-votes pull request #6
Opened 2023-12-04 02:34 UTC by FrolovaOS

2023-12-06 05:36 UTC, svok requested changes
Ольга, хорошая работа. В Отус я ее приму. В Crowdproj, пожалуйста, замените lib-cor на kotlin-cor (штатную библиотеку из mavenCentral).

2023-12-06 05:36 UTC, svok commented on lib-cor/src/commonMain/kotlin/ICorExec.kt
> +package com.crowdproj.vote.lib.cor
В crowdproj не нужна lib-cor. Это боевой проект, в нем должны быть только штатные инструменты. В данном случае kotlin-cor

2023-12-27 19:25 UTC, FrolovaOS commented
поправила

2023-12-28 08:03 UTC, svok approved these changes
Ок. Спасибо.

2023-12-28 08:03 UTC, merged